# 作为服务端提供给客户端使用
ClientListenIP1=0.0.0.0
ClientListenPort1=8008

# 作为服务端提供给客户端使用
HttpListenIP1=0.0.0.0
HttpListenPort1=8080

# 作为服务端提供给消息服务器使用
MsgServerListenIP1=0.0.0.0
MsgServerListenPort1=8100

# 消息服务器地址
msfs=http://106.75.230.157:8700/
# 发现获取地址
discovery=http://106.75.230.157/api/discovery